java_test(
    name = "StripeTest",
    srcs = [
        "StripeTest.java",
    ],
    deps = [
        "//java/com/elfin:stripe",
        "@maven//:junit_junit",
        "@maven//:com_google_truth_truth",
    ]
)